server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php index.html;

    # Serve arquivos estáticos direto
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Processa os arquivos PHP via fastcgi
    location ~ \.php$ {
        fastcgi_pass laravel:9000; # o nome do serviço PHP no docker-compose
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Bloqueia o acesso a arquivos ocultos (ex: .env, .git)
    location ~ /\. {
        deny all;
    }
}
